[package]
name = "krateus-simulation"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[lib]
bench = false

[lints]
workspace = true

[dependencies]
krateus-core.workspace = true
krateus-ecs.workspace = true
